// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpfbkbekaarslkoutntp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwZmJrYmVrYWFyc2xrb3V0bnRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5Nzk0NzEsImV4cCI6MjA2MzU1NTQ3MX0.QWMciPZERgRXoP16oswPiNIMIlteaLu39O0PxS8wUxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);